import type { Metadata } from "next";
import fs from "fs";
import path from "path";
import * as XLSX from "xlsx";
import CertificatesClient from "@/components/CertificatesClient";

export const metadata: Metadata = {
  title: "Certificates",
  description: "Verify and download your official AURON Technical Forum event certificates instantly.",
};

// Helper function to auto-generate data.json from a .xlsx file if missing
function autoGenerateDataJson(folderPath: string, folderName: string): boolean {
  try {
    const files = fs.readdirSync(folderPath);
    const xlsxFile = files.find((f) => f.endsWith(".xlsx"));
    if (!xlsxFile) return false;

    const xlsxPath = path.join(folderPath, xlsxFile);
    const workbook = XLSX.readFile(xlsxPath);
    const firstSheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[firstSheetName];
    
    // Parse sheet as an array of arrays
    const rows = XLSX.utils.sheet_to_json<any[]>(worksheet, { header: 1 });
    if (!rows || rows.length < 2 || !rows[0]) {
      console.error(`Invalid or empty Excel file in folder: ${folderName}`);
      return false;
    }

    // Sanitize headers
    const headers = rows[0].map((h) => (h ? String(h).trim().toLowerCase() : ""));
    
    const nameIdx = headers.findIndex((h) => h.includes("name"));
    const usnIdx = headers.findIndex((h) => h.includes("usn"));
    const certIdx = headers.findIndex((h) => h.includes("certificate") || h.includes("type"));

    if (nameIdx === -1 || usnIdx === -1) {
      console.error(`Missing required 'Name' or 'USN' columns in Excel sheet in folder: ${folderName}`);
      return false;
    }

    const participants = [];
    for (let i = 1; i < rows.length; i++) {
      const row = rows[i];
      if (!row || row.length === 0) continue;
      
      const nameVal = row[nameIdx];
      const usnVal = row[usnIdx];
      if (!nameVal || !usnVal) continue;

      const name = String(nameVal).trim();
      const usn = String(usnVal).trim().toUpperCase();
      const certificate = certIdx !== -1 && row[certIdx] ? String(row[certIdx]).trim().toLowerCase() : "participation";

      participants.push({
        name,
        usn,
        certificate,
      });
    }

    // Map display name
    let eventName = folderName;
    if (folderName === "canva-event") {
      eventName = "Ctrl+Create";
    } else if (folderName === "cyber-hunt") {
      eventName = "Cyber Hunt";
    } else {
      // Format capitalized words from folder name
      eventName = folderName
        .replace(/[-_]+/g, " ")
        .split(" ")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ");
    }

    const eventData = {
      eventName,
      participants,
    };

    const jsonPath = path.join(folderPath, "data.json");
    fs.writeFileSync(jsonPath, JSON.stringify(eventData, null, 2), "utf8");
    console.log(`[Auto-Importer] Successfully generated data.json for ${folderName} (${participants.length} participants)`);
    return true;
  } catch (error) {
    console.error(`[Auto-Importer] Failed to generate data.json for folder ${folderName}:`, error);
    return false;
  }
}

export default function CertificatesPage() {
  let events: { id: string; name: string }[] = [];

  try {
    const certificatesDir = path.join(process.cwd(), "public", "certificates");
    if (fs.existsSync(certificatesDir)) {
      const folders = fs.readdirSync(certificatesDir).filter((f) =>
        fs.statSync(path.join(certificatesDir, f)).isDirectory()
      );

      events = folders
        .map((folder) => {
          try {
            const folderPath = path.join(certificatesDir, folder);
            const jsonPath = path.join(folderPath, "data.json");
            
            // Automatically process xlsx if data.json is not present
            if (!fs.existsSync(jsonPath)) {
              autoGenerateDataJson(folderPath, folder);
            }

            if (fs.existsSync(jsonPath)) {
              const fileContent = fs.readFileSync(jsonPath, "utf8");
              const data = JSON.parse(fileContent);
              return {
                id: folder,
                name: data.eventName || folder,
              };
            }
          } catch (e) {
            console.error(`Error reading data.json for event directory ${folder}:`, e);
          }
          return null;
        })
        .filter((event): event is { id: string; name: string } => event !== null);
    }
  } catch (error) {
    console.error("Error scanning certificates folder at build/render time:", error);
  }

  // Fallback if no folders found or directory scanning failed
  if (events.length === 0) {
    events = [{ id: "cyber-hunt", name: "Cyber Hunt" }];
  }

  return <CertificatesClient events={events} />;
}
